# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# ! DO NOT EDIT THIS FILE MANUALLY
# ! This file is automatically generated by KPP.jl
# ! Do make modifications to the chemical mechanism, use KPP.jl to generate
# ! the registry, state generator and kpp mechanism callers
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

# A global species list jlkpp_registry containing a global species list
# A metadata list jlkpp_registry_meta containing metadata for global species
# $REGISTRY_SPCLIST$ #

# $REGISTRY_DEFAULT_IC$ #
